AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**"
    - "db/**"
    - "vendor/**/*"

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude: []

Metrics/MethodLength:
  CountAsOne: ["array", "heredoc"]

Naming/MethodParameterName:
  MinNameLength: 2

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes
